FROM golang:1.22.4-alpine AS healthcheck-builder
WORKDIR /build
RUN echo 'package main' > healthcheck.go && \
    echo '' >> healthcheck.go && \
    echo 'import (' >> healthcheck.go && \
    echo '    "fmt"' >> healthcheck.go && \
    echo '    "net/http"' >> healthcheck.go && \
    echo '    "os"' >> healthcheck.go && \
    echo '    "time"' >> healthcheck.go && \
    echo ')' >> healthcheck.go && \
    echo '' >> healthcheck.go && \
    echo 'func main() {' >> healthcheck.go && \
    echo '    client := &http.Client{Timeout: 10 * time.Second}' >> healthcheck.go && \
    echo '    resp, err := client.Get("http://localhost:3001")' >> healthcheck.go && \
    echo '    if err != nil {' >> healthcheck.go && \
    echo '        fmt.Fprintf(os.Stderr, "Health check failed: %v\\n", err)' >> healthcheck.go && \
    echo '        os.Exit(1)' >> healthcheck.go && \
    echo '    }' >> healthcheck.go && \
    echo '    defer resp.Body.Close()' >> healthcheck.go && \
    echo '    if resp.StatusCode != 200 {' >> healthcheck.go && \
    echo '        fmt.Fprintf(os.Stderr, "Unexpected status code: %d\\n", resp.StatusCode)' >> healthcheck.go && \
    echo '        os.Exit(1)' >> healthcheck.go && \
    echo '    }' >> healthcheck.go && \
    echo '    fmt.Println("Health check passed")' >> healthcheck.go && \
    echo '}' >> healthcheck.go && \
    go build -ldflags="-w -s" -trimpath -o healthcheck healthcheck.go

FROM louislam/uptime-kuma:beta-rootless
USER root
COPY --from=healthcheck-builder /build/healthcheck /app/extra/healthcheck
RUN chmod +x /app/extra/healthcheck && \
    chown 10014:10014 /app/extra/healthcheck
USER 10014
